/* ============================================================
   NURSING SUCCESS HUB
   MASTER TEMPLATE - PRODUCT REGISTRY V1.1
   ============================================================ */

const PRODUCTS = {
    template: {
        id: "template",
        title: "Quiz App Master Template",
        label: "PRACTICE QUIZ",
        subtitle: "Reusable adaptive quiz template for nursing education.",
        questionBank: "questions/template.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_template_progress_v1_1"
    },
    "community-public-health-nursing": {
        id: "community-public-health-nursing",
        title: "Community & Public Health Nursing",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Community & Public Health Nursing.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_community-public-health-nursing_progress_v1_1"
    },
    "emergency-disaster-nursing": {
        id: "emergency-disaster-nursing",
        title: "Emergency & Disaster Nursing",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Emergency & Disaster Nursing.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_emergency-disaster-nursing_progress_v1_1"
    },
    "fluid-acid-base-balance": {
        id: "fluid-acid-base-balance",
        title: "Fluid & Acid-Base Balance",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Fluid & Acid-Base Balance.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_fluid-acid-base-balance_progress_v1_1"
    },
    "gerontological-nursing": {
        id: "gerontological-nursing",
        title: "Gerontological Nursing",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Gerontological Nursing.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_gerontological-nursing_progress_v1_1"
    },
    "hesi-nursing": {
        id: "hesi-nursing",
        title: "HESI Nursing",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/HESI Nursing.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_hesi-nursing_progress_v1_1"
    },
    "infection-control-prevention": {
        id: "infection-control-prevention",
        title: "Infection Control & Prevention",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Infection Control & Prevention.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_infection-control-prevention_progress_v1_1"
    },
    "medical-surgical-nursing": {
        id: "medical-surgical-nursing",
        title: "Medical Surgical Nursing",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Medical Surgical Nursing.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_medical-surgical-nursing_progress_v1_1"
    },
    "nclex-clinical-judgment": {
        id: "nclex-clinical-judgment",
        title: "NCLEX Clinical Judgment",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/NCLEX Clinical Judgment.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nclex-clinical-judgment_progress_v1_1"
    },
    "nclex-comprehensive-practice": {
        id: "nclex-comprehensive-practice",
        title: "NCLEX Comprehensive Practice",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/NCLEX Comprehensive Practice.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nclex-comprehensive-practice_progress_v1_1"
    },
    "nclex-ngn-case-studies": {
        id: "nclex-ngn-case-studies",
        title: "NCLEX NGN Case Studies",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/NCLEX NGN Case Studies.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nclex-ngn-case-studies_progress_v1_1"
    },
    "nclex-pharmacology": {
        id: "nclex-pharmacology",
        title: "NCLEX Pharmacology",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/NCLEX Pharmacology.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nclex-pharmacology_progress_v1_1"
    },
    "nclex-prioritization-delegation": {
        id: "nclex-prioritization-delegation",
        title: "NCLEX Prioritization & Delegation",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/NCLEX Prioritization & Delegation.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nclex-prioritization-delegation_progress_v1_1"
    },
    "nclex": {
        id: "nclex",
        title: "NCLEX-RN Practice Questions",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/nclex.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nclex_progress_v1_1"
    },
    "nursing-assessment": {
        id: "nursing-assessment",
        title: "Nursing Assessment",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Nursing Assessment.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nursing-assessment_progress_v1_1"
    },
    "nursing-communication-therapeutic-communication": {
        id: "nursing-communication-therapeutic-communication",
        title: "Nursing Communication & Therapeutic Communication",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Nursing Communication & Therapeutic Communication.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nursing-communication-therapeutic-communication_progress_v1_1"
    },
    "nursing-ethics-legal-professional-practice": {
        id: "nursing-ethics-legal-professional-practice",
        title: "Nursing Ethics_ Legal & Professional Practice",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Nursing Ethics_ Legal & Professional Practice.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nursing-ethics-legal-professional-practice_progress_v1_1"
    },
    "nursing-fundamentals-skills": {
        id: "nursing-fundamentals-skills",
        title: "Nursing Fundamentals & Skills",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Nursing Fundamentals & Skills.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nursing-fundamentals-skills_progress_v1_1"
    },
    "nursing-leadership-management": {
        id: "nursing-leadership-management",
        title: "Nursing Leadership & Management",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Nursing Leadership & Management.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nursing-leadership-management_progress_v1_1"
    },
    "nursing-research-evidence-based-practice": {
        id: "nursing-research-evidence-based-practice",
        title: "Nursing Research & Evidence-Based Practice",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Nursing Research & Evidence-Based Practice.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_nursing-research-evidence-based-practice_progress_v1_1"
    },
    "oncology-nursing": {
        id: "oncology-nursing",
        title: "Oncology Nursing",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Oncology Nursing.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_oncology-nursing_progress_v1_1"
    },
    "wound-care-skin-integrity": {
        id: "wound-care-skin-integrity",
        title: "Wound Care & Skin Integrity",
        label: "PRACTICE QUIZ",
        subtitle: "Test your knowledge with an interactive practice quiz designed for structured review.",
        questionBank: "questions/Wound Care & Skin Integrity.js",
        gumroadUrl: "#",
        gumroadButtonText: "GET STUDY GUIDE ->",
        questionsPerPage: 5,
        showProgress: true,
        showAnswerReview: true,
        persistProgress: true,
        storageKey: "nsh_master_quiz_wound-care-skin-integrity_progress_v1_1"
    }
};
